services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ORIGIN: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tf2dle
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - tf2dle_network

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tf2dle
    ports:
      - 5432:5432
    volumes:
      - tf2dle-test-db:/var/lib/postgresql/data
    networks:
      - tf2dle_network

volumes:
  tf2dle-test-db:

networks:
  tf2dle_network:
    name: tf2dle_network
    driver: bridge
